version: 2

jobs:
  build:
    working_directory: ~/perfplot
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .[all]
      # The actual test
      - run: pylint setup.py perfplot/ test/*.py
      - run: cd test/ && MPLBACKEND=Agg pytest --cov perfplot
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
