version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov black flake8
      - checkout
      - run: pip3 install .[all]
      # format & lint
      - run: black --check setup.py perfplot/ test/*.py
      - run: flake8 setup.py perfplot/ test/*.py
      # The actual test
      - run: cd test/ && MPLBACKEND=Agg pytest --cov perfplot
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash) -R ~/work
